// Common foods with accurate macros per typical serving
// Used as instant local results + fallback when Open Food Facts is down
// Sources: USDA FoodData Central, nutrition labels
// ~500 entries covering all major food categories

export const COMMON_FOODS = [
  // ============================================================
  // EGGS & DAIRY (~30)
  // ============================================================
  { name: 'Egg (large, whole)', calories: 72, protein: 6, fat: 5, carbs: 0, fiber: 0, serving: '1 egg (50g)' },
  { name: 'Eggs (2 large)', calories: 144, protein: 12, fat: 10, carbs: 0, fiber: 0, serving: '2 eggs (100g)' },
  { name: 'Eggs (3 large)', calories: 216, protein: 18, fat: 15, carbs: 0, fiber: 0, serving: '3 eggs (150g)' },
  { name: 'Egg whites (large)', calories: 17, protein: 4, fat: 0, carbs: 0, fiber: 0, serving: '1 white (33g)' },
  { name: 'Hard boiled egg', calories: 78, protein: 6, fat: 5, carbs: 1, fiber: 0, serving: '1 egg (50g)' },
  { name: 'Fried egg', calories: 90, protein: 6, fat: 7, carbs: 0, fiber: 0, serving: '1 egg' },
  { name: 'Poached egg', calories: 72, protein: 6, fat: 5, carbs: 0, fiber: 0, serving: '1 egg' },
  { name: 'Scrambled egg (1)', calories: 91, protein: 6, fat: 7, carbs: 1, fiber: 0, serving: '1 egg' },
  { name: 'Greek yoghurt (plain)', calories: 100, protein: 17, fat: 1, carbs: 6, fiber: 0, serving: '170g' },
  { name: 'Greek yoghurt (full fat)', calories: 150, protein: 12, fat: 8, carbs: 8, fiber: 0, serving: '170g' },
  { name: 'Yoghurt (vanilla, low fat)', calories: 154, protein: 6, fat: 2, carbs: 28, fiber: 0, serving: '170g' },
  { name: 'Yoghurt (natural, whole)', calories: 104, protein: 6, fat: 5, carbs: 8, fiber: 0, serving: '150g' },
  { name: 'Milk (full cream)', calories: 150, protein: 8, fat: 8, carbs: 12, fiber: 0, serving: '250ml' },
  { name: 'Milk (skim)', calories: 90, protein: 9, fat: 0, carbs: 13, fiber: 0, serving: '250ml' },
  { name: 'Milk (semi-skim / lite)', calories: 120, protein: 8, fat: 5, carbs: 12, fiber: 0, serving: '250ml' },
  { name: 'Almond milk (unsweetened)', calories: 30, protein: 1, fat: 3, carbs: 1, fiber: 0, serving: '250ml' },
  { name: 'Oat milk', calories: 120, protein: 3, fat: 5, carbs: 16, fiber: 2, serving: '250ml' },
  { name: 'Soy milk (unsweetened)', calories: 80, protein: 7, fat: 4, carbs: 4, fiber: 1, serving: '250ml' },
  { name: 'Cheddar cheese', calories: 113, protein: 7, fat: 9, carbs: 0, fiber: 0, serving: '28g' },
  { name: 'Mozzarella cheese', calories: 85, protein: 6, fat: 6, carbs: 1, fiber: 0, serving: '28g' },
  { name: 'Parmesan cheese (grated)', calories: 110, protein: 10, fat: 7, carbs: 1, fiber: 0, serving: '28g' },
  { name: 'Cream cheese', calories: 99, protein: 2, fat: 10, carbs: 1, fiber: 0, serving: '28g' },
  { name: 'Feta cheese', calories: 75, protein: 4, fat: 6, carbs: 1, fiber: 0, serving: '28g' },
  { name: 'Cottage cheese (low fat)', calories: 81, protein: 14, fat: 1, carbs: 3, fiber: 0, serving: '113g' },
  { name: 'Ricotta', calories: 85, protein: 7, fat: 5, carbs: 3, fiber: 0, serving: '60g' },
  { name: 'Brie cheese', calories: 95, protein: 6, fat: 8, carbs: 0, fiber: 0, serving: '28g' },
  { name: 'Swiss cheese', calories: 106, protein: 8, fat: 8, carbs: 1, fiber: 0, serving: '28g' },
  { name: 'Butter', calories: 102, protein: 0, fat: 12, carbs: 0, fiber: 0, serving: '14g' },
  { name: 'Thickened cream', calories: 51, protein: 0, fat: 5, carbs: 1, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Sour cream', calories: 23, protein: 0, fat: 2, carbs: 1, fiber: 0, serving: '1 tbsp (15g)' },

  // ============================================================
  // PROTEINS (~55)
  // ============================================================
  { name: 'Chicken breast (cooked)', calories: 165, protein: 31, fat: 4, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Chicken thigh (cooked)', calories: 209, protein: 26, fat: 11, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Chicken drumstick (cooked)', calories: 172, protein: 28, fat: 6, carbs: 0, fiber: 0, serving: '1 drumstick (96g)' },
  { name: 'Chicken wing (cooked)', calories: 99, protein: 9, fat: 7, carbs: 0, fiber: 0, serving: '1 wing (34g)' },
  { name: 'Chicken tenderloins (cooked)', calories: 148, protein: 30, fat: 2, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Rotisserie chicken (breast)', calories: 190, protein: 28, fat: 8, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Beef mince (lean)', calories: 250, protein: 26, fat: 15, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Beef mince (regular)', calories: 290, protein: 24, fat: 21, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Beef steak (sirloin)', calories: 206, protein: 26, fat: 11, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Beef steak (scotch fillet / ribeye)', calories: 271, protein: 24, fat: 19, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Beef steak (eye fillet / tenderloin)', calories: 196, protein: 26, fat: 10, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Beef steak (rump)', calories: 215, protein: 27, fat: 11, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Corned beef (silverside)', calories: 180, protein: 25, fat: 8, carbs: 1, fiber: 0, serving: '100g' },
  { name: 'Lamb chop (grilled)', calories: 250, protein: 25, fat: 16, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Lamb mince', calories: 282, protein: 24, fat: 20, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Lamb leg roast', calories: 210, protein: 27, fat: 11, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Pork chop (lean)', calories: 187, protein: 26, fat: 8, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Pork loin (cooked)', calories: 196, protein: 27, fat: 9, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Pork belly (roasted)', calories: 380, protein: 19, fat: 33, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Pulled pork', calories: 210, protein: 24, fat: 12, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Bacon (2 rashers)', calories: 86, protein: 6, fat: 7, carbs: 0, fiber: 0, serving: '2 rashers (30g)' },
  { name: 'Bacon (short cut, 2 rashers)', calories: 110, protein: 13, fat: 6, carbs: 0, fiber: 0, serving: '2 rashers (50g)' },
  { name: 'Turkey breast (cooked)', calories: 135, protein: 30, fat: 1, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Turkey mince (cooked)', calories: 170, protein: 27, fat: 7, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Salmon fillet', calories: 208, protein: 20, fat: 13, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Smoked salmon', calories: 117, protein: 18, fat: 4, carbs: 0, fiber: 0, serving: '56g (2 slices)' },
  { name: 'Tuna (canned in water)', calories: 116, protein: 26, fat: 1, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Tuna (canned in oil)', calories: 186, protein: 26, fat: 8, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Tuna steak (cooked)', calories: 184, protein: 30, fat: 6, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Barramundi (cooked)', calories: 110, protein: 23, fat: 2, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Cod fillet (cooked)', calories: 105, protein: 23, fat: 1, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Snapper fillet (cooked)', calories: 128, protein: 26, fat: 2, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Fish fingers (frozen, 4)', calories: 200, protein: 10, fat: 8, carbs: 20, fiber: 1, serving: '4 fingers (100g)' },
  { name: 'Prawns (cooked)', calories: 99, protein: 24, fat: 0, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Calamari (grilled)', calories: 116, protein: 20, fat: 2, carbs: 4, fiber: 0, serving: '100g' },
  { name: 'Mussels (cooked)', calories: 172, protein: 24, fat: 5, carbs: 7, fiber: 0, serving: '100g' },
  { name: 'Crab meat', calories: 97, protein: 19, fat: 2, carbs: 0, fiber: 0, serving: '100g' },
  { name: 'Tofu (firm)', calories: 76, protein: 8, fat: 5, carbs: 2, fiber: 0, serving: '100g' },
  { name: 'Tempeh', calories: 192, protein: 20, fat: 11, carbs: 8, fiber: 0, serving: '100g' },
  { name: 'Protein powder (whey)', calories: 120, protein: 24, fat: 2, carbs: 3, fiber: 0, serving: '1 scoop (30g)' },
  { name: 'Protein powder (plant)', calories: 110, protein: 20, fat: 2, carbs: 5, fiber: 2, serving: '1 scoop (30g)' },
  { name: 'Protein bar', calories: 210, protein: 20, fat: 7, carbs: 22, fiber: 3, serving: '1 bar (60g)' },
  { name: 'Ham (deli sliced)', calories: 60, protein: 10, fat: 2, carbs: 1, fiber: 0, serving: '2 slices (50g)' },
  { name: 'Salami', calories: 105, protein: 6, fat: 9, carbs: 0, fiber: 0, serving: '28g (4 slices)' },
  { name: 'Prosciutto', calories: 80, protein: 8, fat: 5, carbs: 0, fiber: 0, serving: '28g (2 slices)' },
  { name: 'Chicken deli breast', calories: 50, protein: 10, fat: 1, carbs: 1, fiber: 0, serving: '2 slices (50g)' },
  { name: 'Roast beef (deli)', calories: 65, protein: 11, fat: 2, carbs: 1, fiber: 0, serving: '2 slices (50g)' },
  { name: 'Sausages (beef, 1)', calories: 195, protein: 11, fat: 16, carbs: 2, fiber: 0, serving: '1 sausage (68g)' },
  { name: 'Kangaroo steak (cooked)', calories: 143, protein: 28, fat: 3, carbs: 0, fiber: 0, serving: '100g' },

  // ============================================================
  // GRAINS & CARBS (~42)
  // ============================================================
  { name: 'White rice (cooked)', calories: 130, protein: 3, fat: 0, carbs: 28, fiber: 0, serving: '100g' },
  { name: 'White rice (cooked, 1 cup)', calories: 206, protein: 4, fat: 0, carbs: 45, fiber: 1, serving: '1 cup (158g)' },
  { name: 'Brown rice (cooked)', calories: 112, protein: 2, fat: 1, carbs: 24, fiber: 2, serving: '100g' },
  { name: 'Basmati rice (cooked)', calories: 150, protein: 3, fat: 0, carbs: 33, fiber: 1, serving: '1 cup (163g)' },
  { name: 'Jasmine rice (cooked)', calories: 181, protein: 4, fat: 0, carbs: 40, fiber: 0, serving: '1 cup (158g)' },
  { name: 'Pasta (cooked)', calories: 131, protein: 5, fat: 1, carbs: 25, fiber: 2, serving: '100g' },
  { name: 'Pasta (cooked, 1 cup)', calories: 220, protein: 8, fat: 1, carbs: 43, fiber: 3, serving: '1 cup (140g)' },
  { name: 'Wholemeal pasta (cooked)', calories: 124, protein: 5, fat: 1, carbs: 24, fiber: 4, serving: '100g' },
  { name: 'Egg noodles (cooked)', calories: 138, protein: 5, fat: 2, carbs: 25, fiber: 1, serving: '100g' },
  { name: 'Rice noodles (cooked)', calories: 108, protein: 1, fat: 0, carbs: 24, fiber: 1, serving: '100g' },
  { name: 'Ramen noodles (instant)', calories: 380, protein: 9, fat: 14, carbs: 54, fiber: 2, serving: '1 packet (85g dry)' },
  { name: 'Couscous (cooked)', calories: 112, protein: 4, fat: 0, carbs: 23, fiber: 1, serving: '100g' },
  { name: 'Quinoa (cooked)', calories: 120, protein: 4, fat: 2, carbs: 21, fiber: 3, serving: '100g' },
  { name: 'Oats (dry)', calories: 150, protein: 5, fat: 3, carbs: 27, fiber: 4, serving: '40g' },
  { name: 'Oats (cooked / porridge)', calories: 158, protein: 6, fat: 3, carbs: 27, fiber: 4, serving: '1 cup (234g)' },
  { name: 'Bread (wholemeal, 1 slice)', calories: 82, protein: 4, fat: 1, carbs: 14, fiber: 2, serving: '1 slice (36g)' },
  { name: 'Bread (white, 1 slice)', calories: 79, protein: 3, fat: 1, carbs: 15, fiber: 1, serving: '1 slice (30g)' },
  { name: 'Bread (sourdough, 1 slice)', calories: 90, protein: 4, fat: 1, carbs: 17, fiber: 1, serving: '1 slice (36g)' },
  { name: 'Bread (rye, 1 slice)', calories: 83, protein: 3, fat: 1, carbs: 15, fiber: 2, serving: '1 slice (32g)' },
  { name: 'Bread roll (white)', calories: 140, protein: 5, fat: 2, carbs: 25, fiber: 1, serving: '1 roll (50g)' },
  { name: 'Bagel (plain)', calories: 270, protein: 10, fat: 2, carbs: 53, fiber: 2, serving: '1 bagel (95g)' },
  { name: 'English muffin', calories: 134, protein: 5, fat: 1, carbs: 26, fiber: 2, serving: '1 muffin (57g)' },
  { name: 'Wraps (large flour)', calories: 210, protein: 6, fat: 5, carbs: 36, fiber: 2, serving: '1 wrap (64g)' },
  { name: 'Wraps (wholemeal)', calories: 180, protein: 7, fat: 4, carbs: 29, fiber: 4, serving: '1 wrap (60g)' },
  { name: 'Pita bread', calories: 165, protein: 5, fat: 1, carbs: 33, fiber: 1, serving: '1 pita (60g)' },
  { name: 'Naan bread', calories: 260, protein: 9, fat: 5, carbs: 45, fiber: 2, serving: '1 naan (90g)' },
  { name: 'Crumpet', calories: 85, protein: 3, fat: 0, carbs: 18, fiber: 1, serving: '1 crumpet (45g)' },
  { name: 'Sweet potato (baked)', calories: 103, protein: 2, fat: 0, carbs: 24, fiber: 4, serving: '100g' },
  { name: 'Potato (baked)', calories: 93, protein: 2, fat: 0, carbs: 21, fiber: 2, serving: '100g' },
  { name: 'Potato (mashed)', calories: 113, protein: 2, fat: 4, carbs: 17, fiber: 1, serving: '100g' },
  { name: 'Hot chips / fries', calories: 312, protein: 3, fat: 15, carbs: 41, fiber: 4, serving: 'medium serve (150g)' },
  { name: 'Hash brown', calories: 140, protein: 1, fat: 8, carbs: 16, fiber: 1, serving: '1 patty (56g)' },
  { name: 'Corn tortilla', calories: 52, protein: 1, fat: 1, carbs: 11, fiber: 1, serving: '1 tortilla (26g)' },
  { name: 'Flour tortilla (small)', calories: 90, protein: 2, fat: 2, carbs: 15, fiber: 1, serving: '1 tortilla (30g)' },
  { name: 'Weet-Bix (2 biscuits)', calories: 120, protein: 4, fat: 1, carbs: 22, fiber: 3, serving: '2 biscuits (30g)' },
  { name: 'Cereal (Cornflakes, 1 cup)', calories: 100, protein: 2, fat: 0, carbs: 24, fiber: 1, serving: '1 cup (30g)' },
  { name: 'Cereal (Nutri-Grain)', calories: 115, protein: 3, fat: 1, carbs: 24, fiber: 1, serving: '30g' },
  { name: 'Cereal (Special K)', calories: 117, protein: 5, fat: 1, carbs: 23, fiber: 1, serving: '31g' },
  { name: 'Muesli (natural)', calories: 200, protein: 5, fat: 6, carbs: 30, fiber: 4, serving: '50g' },
  { name: 'Granola', calories: 230, protein: 5, fat: 9, carbs: 33, fiber: 3, serving: '50g' },
  { name: 'Polenta (cooked)', calories: 70, protein: 2, fat: 0, carbs: 15, fiber: 1, serving: '100g' },
  { name: 'Gnocchi (cooked)', calories: 130, protein: 3, fat: 1, carbs: 27, fiber: 1, serving: '100g' },

  // ============================================================
  // FRUITS (~37)
  // ============================================================
  { name: 'Banana', calories: 105, protein: 1, fat: 0, carbs: 27, fiber: 3, serving: '1 medium (118g)' },
  { name: 'Apple', calories: 95, protein: 0, fat: 0, carbs: 25, fiber: 4, serving: '1 medium (182g)' },
  { name: 'Orange', calories: 62, protein: 1, fat: 0, carbs: 15, fiber: 3, serving: '1 medium (131g)' },
  { name: 'Mandarin', calories: 40, protein: 1, fat: 0, carbs: 9, fiber: 1, serving: '1 medium (76g)' },
  { name: 'Grapes (red or green)', calories: 104, protein: 1, fat: 0, carbs: 27, fiber: 1, serving: '1 cup (151g)' },
  { name: 'Blueberries', calories: 84, protein: 1, fat: 0, carbs: 21, fiber: 4, serving: '1 cup (148g)' },
  { name: 'Strawberries', calories: 49, protein: 1, fat: 0, carbs: 12, fiber: 3, serving: '1 cup (152g)' },
  { name: 'Raspberries', calories: 64, protein: 1, fat: 1, carbs: 15, fiber: 8, serving: '1 cup (123g)' },
  { name: 'Blackberries', calories: 62, protein: 2, fat: 1, carbs: 14, fiber: 8, serving: '1 cup (144g)' },
  { name: 'Mango', calories: 99, protein: 1, fat: 1, carbs: 25, fiber: 3, serving: '1 cup (165g)' },
  { name: 'Pineapple', calories: 82, protein: 1, fat: 0, carbs: 22, fiber: 2, serving: '1 cup (165g)' },
  { name: 'Watermelon', calories: 46, protein: 1, fat: 0, carbs: 11, fiber: 1, serving: '1 cup (152g)' },
  { name: 'Rockmelon / cantaloupe', calories: 54, protein: 1, fat: 0, carbs: 13, fiber: 1, serving: '1 cup (160g)' },
  { name: 'Kiwi fruit', calories: 42, protein: 1, fat: 0, carbs: 10, fiber: 2, serving: '1 medium (69g)' },
  { name: 'Pear', calories: 101, protein: 1, fat: 0, carbs: 27, fiber: 6, serving: '1 medium (178g)' },
  { name: 'Peach', calories: 59, protein: 1, fat: 0, carbs: 14, fiber: 2, serving: '1 medium (150g)' },
  { name: 'Nectarine', calories: 62, protein: 2, fat: 0, carbs: 15, fiber: 2, serving: '1 medium (142g)' },
  { name: 'Plum', calories: 30, protein: 0, fat: 0, carbs: 8, fiber: 1, serving: '1 medium (66g)' },
  { name: 'Cherries', calories: 87, protein: 1, fat: 0, carbs: 22, fiber: 3, serving: '1 cup (138g)' },
  { name: 'Avocado (half)', calories: 161, protein: 2, fat: 15, carbs: 9, fiber: 7, serving: '1/2 (100g)' },
  { name: 'Avocado (whole)', calories: 322, protein: 4, fat: 29, carbs: 17, fiber: 13, serving: '1 (200g)' },
  { name: 'Passionfruit', calories: 17, protein: 0, fat: 0, carbs: 4, fiber: 2, serving: '1 fruit (18g)' },
  { name: 'Pomegranate seeds', calories: 72, protein: 1, fat: 1, carbs: 16, fiber: 4, serving: '1/2 cup (87g)' },
  { name: 'Lemon', calories: 17, protein: 1, fat: 0, carbs: 5, fiber: 2, serving: '1 medium (58g)' },
  { name: 'Lime', calories: 11, protein: 0, fat: 0, carbs: 4, fiber: 1, serving: '1 medium (44g)' },
  { name: 'Grapefruit', calories: 52, protein: 1, fat: 0, carbs: 13, fiber: 2, serving: '1/2 (123g)' },
  { name: 'Papaya', calories: 62, protein: 1, fat: 0, carbs: 16, fiber: 3, serving: '1 cup (145g)' },
  { name: 'Dragonfruit', calories: 60, protein: 1, fat: 0, carbs: 13, fiber: 3, serving: '1 small (100g)' },
  { name: 'Dates (Medjool)', calories: 133, protein: 1, fat: 0, carbs: 36, fiber: 3, serving: '2 dates (48g)' },
  { name: 'Raisins / sultanas', calories: 130, protein: 1, fat: 0, carbs: 34, fiber: 2, serving: '1/4 cup (40g)' },
  { name: 'Dried apricots', calories: 78, protein: 1, fat: 0, carbs: 20, fiber: 2, serving: '28g (5 halves)' },
  { name: 'Dried cranberries', calories: 123, protein: 0, fat: 1, carbs: 33, fiber: 2, serving: '40g' },
  { name: 'Mixed frozen berries', calories: 70, protein: 1, fat: 0, carbs: 17, fiber: 4, serving: '1 cup (140g)' },
  { name: 'Frozen mango', calories: 90, protein: 1, fat: 0, carbs: 23, fiber: 2, serving: '1 cup (150g)' },
  { name: 'Banana (frozen)', calories: 105, protein: 1, fat: 0, carbs: 27, fiber: 3, serving: '1 medium (118g)' },
  { name: 'Apple sauce (unsweetened)', calories: 50, protein: 0, fat: 0, carbs: 14, fiber: 1, serving: '1/2 cup (122g)' },
  { name: 'Coconut (desiccated)', calories: 133, protein: 1, fat: 13, carbs: 5, fiber: 3, serving: '20g' },

  // ============================================================
  // VEGETABLES (~42)
  // ============================================================
  { name: 'Broccoli (cooked)', calories: 55, protein: 4, fat: 1, carbs: 11, fiber: 5, serving: '1 cup (156g)' },
  { name: 'Spinach (raw)', calories: 7, protein: 1, fat: 0, carbs: 1, fiber: 1, serving: '1 cup (30g)' },
  { name: 'Spinach (cooked)', calories: 41, protein: 5, fat: 0, carbs: 7, fiber: 4, serving: '1 cup (180g)' },
  { name: 'Mixed salad greens', calories: 10, protein: 1, fat: 0, carbs: 2, fiber: 1, serving: '1 cup (50g)' },
  { name: 'Lettuce (iceberg)', calories: 8, protein: 1, fat: 0, carbs: 2, fiber: 1, serving: '1 cup shredded (55g)' },
  { name: 'Kale (raw)', calories: 33, protein: 3, fat: 1, carbs: 6, fiber: 1, serving: '1 cup (67g)' },
  { name: 'Tomato', calories: 22, protein: 1, fat: 0, carbs: 5, fiber: 1, serving: '1 medium (123g)' },
  { name: 'Cherry tomatoes', calories: 27, protein: 1, fat: 0, carbs: 6, fiber: 2, serving: '1 cup (149g)' },
  { name: 'Cucumber', calories: 16, protein: 1, fat: 0, carbs: 4, fiber: 1, serving: '1 cup sliced (119g)' },
  { name: 'Carrot', calories: 25, protein: 1, fat: 0, carbs: 6, fiber: 2, serving: '1 medium (61g)' },
  { name: 'Carrot (cooked)', calories: 54, protein: 1, fat: 0, carbs: 13, fiber: 5, serving: '1 cup (156g)' },
  { name: 'Mushrooms (sliced)', calories: 15, protein: 2, fat: 0, carbs: 2, fiber: 1, serving: '1 cup (70g)' },
  { name: 'Capsicum (bell pepper)', calories: 31, protein: 1, fat: 0, carbs: 7, fiber: 2, serving: '1 medium (119g)' },
  { name: 'Corn (cob)', calories: 88, protein: 3, fat: 1, carbs: 19, fiber: 2, serving: '1 ear (90g)' },
  { name: 'Corn (canned)', calories: 67, protein: 2, fat: 1, carbs: 14, fiber: 2, serving: '1/2 cup (82g)' },
  { name: 'Peas (green, cooked)', calories: 67, protein: 4, fat: 0, carbs: 12, fiber: 4, serving: '1/2 cup (80g)' },
  { name: 'Green beans (cooked)', calories: 35, protein: 2, fat: 0, carbs: 8, fiber: 3, serving: '1 cup (125g)' },
  { name: 'Zucchini (cooked)', calories: 27, protein: 2, fat: 0, carbs: 5, fiber: 2, serving: '1 cup (180g)' },
  { name: 'Eggplant (cooked)', calories: 35, protein: 1, fat: 0, carbs: 9, fiber: 2, serving: '1 cup (99g)' },
  { name: 'Cauliflower (cooked)', calories: 29, protein: 2, fat: 1, carbs: 5, fiber: 2, serving: '1 cup (124g)' },
  { name: 'Asparagus (cooked)', calories: 27, protein: 3, fat: 0, carbs: 5, fiber: 2, serving: '6 spears (90g)' },
  { name: 'Brussels sprouts (cooked)', calories: 56, protein: 4, fat: 1, carbs: 11, fiber: 4, serving: '1 cup (156g)' },
  { name: 'Cabbage (raw, shredded)', calories: 17, protein: 1, fat: 0, carbs: 4, fiber: 2, serving: '1 cup (70g)' },
  { name: 'Onion (raw)', calories: 44, protein: 1, fat: 0, carbs: 10, fiber: 2, serving: '1 medium (110g)' },
  { name: 'Garlic', calories: 4, protein: 0, fat: 0, carbs: 1, fiber: 0, serving: '1 clove (3g)' },
  { name: 'Celery', calories: 6, protein: 0, fat: 0, carbs: 1, fiber: 1, serving: '1 stalk (40g)' },
  { name: 'Beetroot (cooked)', calories: 44, protein: 2, fat: 0, carbs: 10, fiber: 2, serving: '100g' },
  { name: 'Edamame (shelled)', calories: 120, protein: 12, fat: 5, carbs: 9, fiber: 4, serving: '1/2 cup (75g)' },
  { name: 'Snow peas', calories: 26, protein: 2, fat: 0, carbs: 5, fiber: 2, serving: '1 cup (63g)' },
  { name: 'Bean sprouts', calories: 31, protein: 3, fat: 0, carbs: 6, fiber: 2, serving: '1 cup (104g)' },
  { name: 'Pumpkin (cooked)', calories: 49, protein: 2, fat: 0, carbs: 12, fiber: 3, serving: '1 cup (245g)' },
  { name: 'Sweet corn (canned)', calories: 67, protein: 2, fat: 1, carbs: 14, fiber: 2, serving: '1/2 cup (82g)' },
  { name: 'Mixed frozen vegetables', calories: 59, protein: 3, fat: 0, carbs: 12, fiber: 4, serving: '1 cup (91g)' },
  { name: 'Roast vegetables (mixed)', calories: 120, protein: 2, fat: 5, carbs: 17, fiber: 3, serving: '1 cup (150g)' },
  { name: 'Kimchi', calories: 15, protein: 1, fat: 0, carbs: 2, fiber: 1, serving: '1/2 cup (75g)' },
  { name: 'Sauerkraut', calories: 13, protein: 1, fat: 0, carbs: 3, fiber: 2, serving: '1/2 cup (71g)' },
  { name: 'Coleslaw', calories: 150, protein: 1, fat: 11, carbs: 13, fiber: 2, serving: '1/2 cup (100g)' },
  { name: 'Olives (green)', calories: 41, protein: 0, fat: 4, carbs: 1, fiber: 1, serving: '8 olives (28g)' },
  { name: 'Olives (kalamata)', calories: 44, protein: 0, fat: 4, carbs: 2, fiber: 1, serving: '8 olives (28g)' },
  { name: 'Jalapeño pepper', calories: 4, protein: 0, fat: 0, carbs: 1, fiber: 0, serving: '1 pepper (14g)' },
  { name: 'Ginger (fresh)', calories: 5, protein: 0, fat: 0, carbs: 1, fiber: 0, serving: '1 tbsp grated (6g)' },
  { name: 'Sun-dried tomatoes', calories: 70, protein: 4, fat: 1, carbs: 15, fiber: 3, serving: '28g (5 pieces)' },

  // ============================================================
  // NUTS & SEEDS (~22)
  // ============================================================
  { name: 'Almonds', calories: 164, protein: 6, fat: 14, carbs: 6, fiber: 4, serving: '28g (23 nuts)' },
  { name: 'Walnuts', calories: 185, protein: 4, fat: 18, carbs: 4, fiber: 2, serving: '28g' },
  { name: 'Cashews', calories: 157, protein: 5, fat: 12, carbs: 9, fiber: 1, serving: '28g' },
  { name: 'Macadamias', calories: 204, protein: 2, fat: 22, carbs: 4, fiber: 2, serving: '28g' },
  { name: 'Peanuts (roasted)', calories: 161, protein: 7, fat: 14, carbs: 5, fiber: 2, serving: '28g' },
  { name: 'Pistachios', calories: 159, protein: 6, fat: 13, carbs: 8, fiber: 3, serving: '28g' },
  { name: 'Pecans', calories: 196, protein: 3, fat: 20, carbs: 4, fiber: 3, serving: '28g' },
  { name: 'Brazil nuts', calories: 186, protein: 4, fat: 19, carbs: 3, fiber: 2, serving: '28g (6 nuts)' },
  { name: 'Hazelnuts', calories: 178, protein: 4, fat: 17, carbs: 5, fiber: 3, serving: '28g' },
  { name: 'Pine nuts', calories: 191, protein: 4, fat: 19, carbs: 4, fiber: 1, serving: '28g' },
  { name: 'Mixed nuts (unsalted)', calories: 172, protein: 5, fat: 15, carbs: 7, fiber: 2, serving: '28g' },
  { name: 'Trail mix', calories: 140, protein: 4, fat: 9, carbs: 13, fiber: 2, serving: '28g' },
  { name: 'Peanut butter', calories: 188, protein: 7, fat: 16, carbs: 7, fiber: 2, serving: '2 tbsp (32g)' },
  { name: 'Almond butter', calories: 196, protein: 7, fat: 18, carbs: 6, fiber: 3, serving: '2 tbsp (32g)' },
  { name: 'Tahini', calories: 89, protein: 3, fat: 8, carbs: 3, fiber: 1, serving: '1 tbsp (15g)' },
  { name: 'Chia seeds', calories: 138, protein: 5, fat: 9, carbs: 12, fiber: 10, serving: '2 tbsp (28g)' },
  { name: 'Flaxseeds (ground)', calories: 37, protein: 1, fat: 3, carbs: 2, fiber: 2, serving: '1 tbsp (7g)' },
  { name: 'Sunflower seeds', calories: 165, protein: 6, fat: 14, carbs: 6, fiber: 3, serving: '28g' },
  { name: 'Pumpkin seeds (pepitas)', calories: 153, protein: 7, fat: 13, carbs: 4, fiber: 1, serving: '28g' },
  { name: 'Hemp seeds', calories: 166, protein: 10, fat: 14, carbs: 3, fiber: 1, serving: '28g' },
  { name: 'Sesame seeds', calories: 52, protein: 2, fat: 4, carbs: 2, fiber: 1, serving: '1 tbsp (9g)' },
  { name: 'LSA mix (linseed, sunflower, almond)', calories: 95, protein: 4, fat: 8, carbs: 2, fiber: 2, serving: '1 tbsp (15g)' },

  // ============================================================
  // LEGUMES (~16)
  // ============================================================
  { name: 'Chickpeas (cooked)', calories: 134, protein: 7, fat: 2, carbs: 22, fiber: 6, serving: '1/2 cup (82g)' },
  { name: 'Chickpeas (canned)', calories: 143, protein: 7, fat: 3, carbs: 23, fiber: 6, serving: '1/2 cup (120g)' },
  { name: 'Black beans (cooked)', calories: 114, protein: 8, fat: 0, carbs: 20, fiber: 8, serving: '1/2 cup (86g)' },
  { name: 'Kidney beans (cooked)', calories: 112, protein: 8, fat: 0, carbs: 20, fiber: 6, serving: '1/2 cup (88g)' },
  { name: 'Lentils (cooked)', calories: 115, protein: 9, fat: 0, carbs: 20, fiber: 8, serving: '1/2 cup (99g)' },
  { name: 'Red lentils (cooked)', calories: 105, protein: 8, fat: 0, carbs: 18, fiber: 5, serving: '1/2 cup (99g)' },
  { name: 'Cannellini beans (cooked)', calories: 110, protein: 8, fat: 0, carbs: 20, fiber: 6, serving: '1/2 cup (90g)' },
  { name: 'Baked beans (canned)', calories: 119, protein: 5, fat: 1, carbs: 21, fiber: 5, serving: '1/2 cup (130g)' },
  { name: 'Lima beans (cooked)', calories: 108, protein: 7, fat: 0, carbs: 20, fiber: 7, serving: '1/2 cup (85g)' },
  { name: 'Navy beans (cooked)', calories: 127, protein: 7, fat: 1, carbs: 24, fiber: 10, serving: '1/2 cup (91g)' },
  { name: 'Pinto beans (cooked)', calories: 122, protein: 8, fat: 1, carbs: 22, fiber: 8, serving: '1/2 cup (86g)' },
  { name: 'Green split peas (cooked)', calories: 116, protein: 8, fat: 0, carbs: 21, fiber: 8, serving: '1/2 cup (98g)' },
  { name: 'Refried beans', calories: 107, protein: 6, fat: 3, carbs: 17, fiber: 5, serving: '1/2 cup (126g)' },
  { name: 'Hummus', calories: 50, protein: 2, fat: 3, carbs: 4, fiber: 1, serving: '2 tbsp (30g)' },
  { name: 'Falafel (baked, 3)', calories: 170, protein: 7, fat: 8, carbs: 18, fiber: 3, serving: '3 balls (75g)' },
  { name: 'Bean mix (4-bean, canned)', calories: 105, protein: 7, fat: 0, carbs: 19, fiber: 6, serving: '1/2 cup (100g)' },

  // ============================================================
  // FATS & OILS (~12)
  // ============================================================
  { name: 'Olive oil', calories: 119, protein: 0, fat: 14, carbs: 0, fiber: 0, serving: '1 tbsp (14ml)' },
  { name: 'Coconut oil', calories: 121, protein: 0, fat: 14, carbs: 0, fiber: 0, serving: '1 tbsp (14ml)' },
  { name: 'Vegetable oil (canola)', calories: 120, protein: 0, fat: 14, carbs: 0, fiber: 0, serving: '1 tbsp (14ml)' },
  { name: 'Sesame oil', calories: 120, protein: 0, fat: 14, carbs: 0, fiber: 0, serving: '1 tbsp (14ml)' },
  { name: 'Avocado oil', calories: 124, protein: 0, fat: 14, carbs: 0, fiber: 0, serving: '1 tbsp (14ml)' },
  { name: 'Cooking spray (olive oil)', calories: 8, protein: 0, fat: 1, carbs: 0, fiber: 0, serving: '1 spray (0.5s)' },
  { name: 'Margarine', calories: 75, protein: 0, fat: 8, carbs: 0, fiber: 0, serving: '1 tbsp (10g)' },
  { name: 'Ghee', calories: 112, protein: 0, fat: 13, carbs: 0, fiber: 0, serving: '1 tbsp (13g)' },
  { name: 'Caesar dressing', calories: 78, protein: 1, fat: 8, carbs: 1, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Italian dressing', calories: 43, protein: 0, fat: 4, carbs: 2, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Balsamic vinaigrette', calories: 50, protein: 0, fat: 4, carbs: 3, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Ranch dressing', calories: 73, protein: 0, fat: 8, carbs: 1, fiber: 0, serving: '1 tbsp (15ml)' },

  // ============================================================
  // DRINKS (~27)
  // ============================================================
  { name: 'Coffee (black)', calories: 2, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 cup (240ml)' },
  { name: 'Coffee with milk', calories: 30, protein: 2, fat: 1, carbs: 3, fiber: 0, serving: '1 cup' },
  { name: 'Flat white', calories: 120, protein: 6, fat: 6, carbs: 8, fiber: 0, serving: '1 cup' },
  { name: 'Latte', calories: 135, protein: 7, fat: 6, carbs: 10, fiber: 0, serving: '1 cup (350ml)' },
  { name: 'Cappuccino', calories: 80, protein: 4, fat: 4, carbs: 6, fiber: 0, serving: '1 cup (200ml)' },
  { name: 'Long black / Americano', calories: 5, protein: 0, fat: 0, carbs: 1, fiber: 0, serving: '1 cup' },
  { name: 'Espresso (single shot)', calories: 3, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '30ml' },
  { name: 'Mocha', calories: 230, protein: 8, fat: 8, carbs: 33, fiber: 1, serving: '1 cup (350ml)' },
  { name: 'Iced coffee (milk-based)', calories: 180, protein: 6, fat: 6, carbs: 25, fiber: 0, serving: '1 cup (350ml)' },
  { name: 'Tea (black, no milk)', calories: 2, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 cup (240ml)' },
  { name: 'Tea (with milk)', calories: 20, protein: 1, fat: 1, carbs: 2, fiber: 0, serving: '1 cup' },
  { name: 'Green tea', calories: 2, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 cup (240ml)' },
  { name: 'Herbal tea', calories: 2, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 cup (240ml)' },
  { name: 'Orange juice', calories: 112, protein: 2, fat: 0, carbs: 26, fiber: 0, serving: '1 cup (248ml)' },
  { name: 'Apple juice', calories: 114, protein: 0, fat: 0, carbs: 28, fiber: 0, serving: '1 cup (248ml)' },
  { name: 'Cranberry juice', calories: 116, protein: 0, fat: 0, carbs: 30, fiber: 0, serving: '1 cup (248ml)' },
  { name: 'Coconut water', calories: 45, protein: 2, fat: 0, carbs: 9, fiber: 0, serving: '1 cup (240ml)' },
  { name: 'Protein shake (whey + milk)', calories: 270, protein: 32, fat: 10, carbs: 15, fiber: 0, serving: '1 shake' },
  { name: 'Protein shake (whey + water)', calories: 130, protein: 25, fat: 2, carbs: 4, fiber: 0, serving: '1 shake' },
  { name: 'Smoothie (banana + berries)', calories: 180, protein: 3, fat: 1, carbs: 42, fiber: 4, serving: '1 cup' },
  { name: 'Coca-Cola', calories: 140, protein: 0, fat: 0, carbs: 39, fiber: 0, serving: '375ml can' },
  { name: 'Coca-Cola Zero', calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '375ml can' },
  { name: 'Sprite / lemonade', calories: 140, protein: 0, fat: 0, carbs: 38, fiber: 0, serving: '375ml can' },
  { name: 'Beer (regular)', calories: 153, protein: 2, fat: 0, carbs: 13, fiber: 0, serving: '375ml (1 stubby)' },
  { name: 'Beer (light)', calories: 99, protein: 1, fat: 0, carbs: 5, fiber: 0, serving: '375ml' },
  { name: 'Red wine', calories: 125, protein: 0, fat: 0, carbs: 4, fiber: 0, serving: '150ml glass' },
  { name: 'White wine', calories: 121, protein: 0, fat: 0, carbs: 4, fiber: 0, serving: '150ml glass' },

  // ============================================================
  // SNACKS (~32)
  // ============================================================
  { name: 'Dark chocolate (70%)', calories: 170, protein: 2, fat: 12, carbs: 13, fiber: 3, serving: '30g' },
  { name: 'Milk chocolate', calories: 155, protein: 2, fat: 9, carbs: 17, fiber: 1, serving: '30g' },
  { name: 'White chocolate', calories: 160, protein: 2, fat: 9, carbs: 17, fiber: 0, serving: '30g' },
  { name: 'Potato chips (plain)', calories: 152, protein: 2, fat: 10, carbs: 15, fiber: 1, serving: '28g' },
  { name: 'Potato chips (small bag)', calories: 274, protein: 3, fat: 17, carbs: 27, fiber: 2, serving: '50g bag' },
  { name: 'Corn chips (Doritos)', calories: 140, protein: 2, fat: 7, carbs: 18, fiber: 1, serving: '28g' },
  { name: 'Pretzels', calories: 108, protein: 3, fat: 1, carbs: 23, fiber: 1, serving: '28g' },
  { name: 'Popcorn (air-popped)', calories: 93, protein: 3, fat: 1, carbs: 19, fiber: 4, serving: '3 cups (24g)' },
  { name: 'Popcorn (buttered, cinema)', calories: 360, protein: 4, fat: 20, carbs: 41, fiber: 6, serving: 'small (60g)' },
  { name: 'Rice cakes (2)', calories: 70, protein: 1, fat: 0, carbs: 15, fiber: 0, serving: '2 cakes (18g)' },
  { name: 'Rice crackers', calories: 110, protein: 2, fat: 1, carbs: 23, fiber: 0, serving: '28g' },
  { name: 'Crackers (water)', calories: 78, protein: 2, fat: 2, carbs: 13, fiber: 1, serving: '4 crackers (20g)' },
  { name: 'Crackers (Jatz / Ritz)', calories: 80, protein: 1, fat: 4, carbs: 10, fiber: 0, serving: '4 crackers (16g)' },
  { name: 'Vita-Weat (4 crackers)', calories: 88, protein: 3, fat: 1, carbs: 15, fiber: 2, serving: '4 crackers (25g)' },
  { name: 'Muesli bar', calories: 150, protein: 3, fat: 5, carbs: 24, fiber: 2, serving: '1 bar (35g)' },
  { name: 'Granola bar (Carman\'s)', calories: 180, protein: 4, fat: 7, carbs: 25, fiber: 2, serving: '1 bar (40g)' },
  { name: 'Fruit & nut bar (Be Natural)', calories: 175, protein: 4, fat: 9, carbs: 20, fiber: 2, serving: '1 bar (40g)' },
  { name: 'Jerky (beef)', calories: 80, protein: 15, fat: 1, carbs: 3, fiber: 0, serving: '28g' },
  { name: 'Dried mango', calories: 128, protein: 1, fat: 0, carbs: 31, fiber: 2, serving: '40g' },
  { name: 'Yoghurt-covered raisins', calories: 130, protein: 1, fat: 5, carbs: 20, fiber: 0, serving: '28g' },
  { name: 'Cheese and crackers', calories: 200, protein: 8, fat: 12, carbs: 14, fiber: 1, serving: '30g cheese + 4 crackers' },
  { name: 'Vegemite on toast', calories: 100, protein: 5, fat: 1, carbs: 16, fiber: 1, serving: '1 slice + 1 tsp' },
  { name: 'Peanut butter on rice cake', calories: 130, protein: 4, fat: 8, carbs: 11, fiber: 1, serving: '1 cake + 1 tbsp PB' },
  { name: 'Apple with peanut butter', calories: 195, protein: 4, fat: 8, carbs: 29, fiber: 5, serving: '1 apple + 1 tbsp PB' },
  { name: 'Celery with peanut butter', calories: 100, protein: 4, fat: 8, carbs: 4, fiber: 2, serving: '2 stalks + 1 tbsp PB' },
  { name: 'Banana bread (1 slice)', calories: 196, protein: 3, fat: 6, carbs: 33, fiber: 1, serving: '1 slice (60g)' },
  { name: 'Bliss ball (date & nut)', calories: 90, protein: 2, fat: 5, carbs: 10, fiber: 1, serving: '1 ball (25g)' },
  { name: 'Corn on the cob (buttered)', calories: 130, protein: 3, fat: 5, carbs: 19, fiber: 2, serving: '1 ear' },
  { name: 'Fruit salad', calories: 80, protein: 1, fat: 0, carbs: 20, fiber: 2, serving: '1 cup (150g)' },
  { name: 'Gelato (1 scoop)', calories: 140, protein: 3, fat: 5, carbs: 21, fiber: 0, serving: '1 scoop (75g)' },
  { name: 'Ice cream (vanilla, 1 scoop)', calories: 137, protein: 2, fat: 7, carbs: 16, fiber: 0, serving: '1 scoop (66g)' },
  { name: 'Frozen yoghurt (1 scoop)', calories: 110, protein: 3, fat: 3, carbs: 18, fiber: 0, serving: '1 scoop (75g)' },

  // ============================================================
  // CONDIMENTS & SAUCES (~22)
  // ============================================================
  { name: 'Tomato sauce / ketchup', calories: 20, protein: 0, fat: 0, carbs: 5, fiber: 0, serving: '1 tbsp (17g)' },
  { name: 'BBQ sauce', calories: 29, protein: 0, fat: 0, carbs: 7, fiber: 0, serving: '1 tbsp (17g)' },
  { name: 'Soy sauce', calories: 9, protein: 1, fat: 0, carbs: 1, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Sweet chilli sauce', calories: 30, protein: 0, fat: 0, carbs: 7, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Sriracha', calories: 15, protein: 0, fat: 0, carbs: 3, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Hot sauce (Tabasco)', calories: 1, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 tsp (5ml)' },
  { name: 'Mayonnaise', calories: 94, protein: 0, fat: 10, carbs: 0, fiber: 0, serving: '1 tbsp (14g)' },
  { name: 'Mayonnaise (light)', calories: 35, protein: 0, fat: 3, carbs: 2, fiber: 0, serving: '1 tbsp (14g)' },
  { name: 'Mustard (yellow)', calories: 3, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 tsp (5g)' },
  { name: 'Mustard (Dijon)', calories: 5, protein: 0, fat: 0, carbs: 0, fiber: 0, serving: '1 tsp (5g)' },
  { name: 'Salsa', calories: 10, protein: 0, fat: 0, carbs: 2, fiber: 0, serving: '2 tbsp (30g)' },
  { name: 'Guacamole', calories: 50, protein: 1, fat: 4, carbs: 3, fiber: 2, serving: '2 tbsp (30g)' },
  { name: 'Honey', calories: 64, protein: 0, fat: 0, carbs: 17, fiber: 0, serving: '1 tbsp (21g)' },
  { name: 'Maple syrup', calories: 52, protein: 0, fat: 0, carbs: 13, fiber: 0, serving: '1 tbsp (20ml)' },
  { name: 'Sugar', calories: 48, protein: 0, fat: 0, carbs: 12, fiber: 0, serving: '1 tbsp (12g)' },
  { name: 'Pesto (basil)', calories: 80, protein: 2, fat: 7, carbs: 2, fiber: 0, serving: '1 tbsp (15g)' },
  { name: 'Teriyaki sauce', calories: 16, protein: 1, fat: 0, carbs: 3, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Fish sauce', calories: 6, protein: 1, fat: 0, carbs: 1, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Oyster sauce', calories: 9, protein: 0, fat: 0, carbs: 2, fiber: 0, serving: '1 tbsp (15ml)' },
  { name: 'Hoisin sauce', calories: 35, protein: 1, fat: 1, carbs: 7, fiber: 0, serving: '1 tbsp (16g)' },
  { name: 'Dulce de leche', calories: 65, protein: 1, fat: 2, carbs: 11, fiber: 0, serving: '1 tbsp (20g)' },
  { name: 'Vegemite', calories: 11, protein: 2, fat: 0, carbs: 1, fiber: 0, serving: '1 tsp (5g)' },

  // ============================================================
  // PREPARED MEALS & COMMON COMBOS (~52)
  // ============================================================
  { name: 'Scrambled eggs (2)', calories: 182, protein: 12, fat: 14, carbs: 2, fiber: 0, serving: '2 eggs' },
  { name: 'Omelette (3 egg)', calories: 280, protein: 20, fat: 20, carbs: 2, fiber: 0, serving: '1 omelette' },
  { name: 'Omelette (3 egg, cheese)', calories: 370, protein: 27, fat: 27, carbs: 2, fiber: 0, serving: '1 omelette' },
  { name: 'Eggs on toast (2 eggs)', calories: 260, protein: 16, fat: 11, carbs: 24, fiber: 2, serving: '2 eggs + 1 slice' },
  { name: 'Chicken wrap', calories: 380, protein: 28, fat: 12, carbs: 38, fiber: 3, serving: '1 wrap' },
  { name: 'Chicken salad', calories: 250, protein: 30, fat: 10, carbs: 8, fiber: 3, serving: '1 bowl' },
  { name: 'Chicken stir fry (with rice)', calories: 450, protein: 30, fat: 12, carbs: 52, fiber: 3, serving: '1 bowl' },
  { name: 'Chicken schnitzel', calories: 320, protein: 28, fat: 16, carbs: 16, fiber: 1, serving: '1 piece (150g)' },
  { name: 'Chicken curry (with rice)', calories: 510, protein: 28, fat: 16, carbs: 58, fiber: 3, serving: '1 bowl' },
  { name: 'Butter chicken (with rice)', calories: 534, protein: 26, fat: 22, carbs: 58, fiber: 2, serving: '1 bowl' },
  { name: 'Beef stir fry (with noodles)', calories: 420, protein: 28, fat: 14, carbs: 44, fiber: 3, serving: '1 bowl' },
  { name: 'Beef bolognese (with pasta)', calories: 520, protein: 28, fat: 18, carbs: 56, fiber: 4, serving: '1 bowl' },
  { name: 'Spaghetti carbonara', calories: 500, protein: 22, fat: 20, carbs: 52, fiber: 2, serving: '1 bowl' },
  { name: 'Mac and cheese', calories: 440, protein: 17, fat: 20, carbs: 46, fiber: 2, serving: '1 bowl (250g)' },
  { name: 'Lasagne', calories: 380, protein: 20, fat: 16, carbs: 36, fiber: 2, serving: '1 piece (250g)' },
  { name: 'Tuna salad sandwich', calories: 350, protein: 22, fat: 14, carbs: 32, fiber: 2, serving: '1 sandwich' },
  { name: 'Ham and cheese sandwich', calories: 340, protein: 18, fat: 14, carbs: 32, fiber: 2, serving: '1 sandwich' },
  { name: 'BLT sandwich', calories: 340, protein: 12, fat: 17, carbs: 32, fiber: 2, serving: '1 sandwich' },
  { name: 'Chicken sandwich', calories: 350, protein: 24, fat: 11, carbs: 35, fiber: 2, serving: '1 sandwich' },
  { name: 'Egg and lettuce sandwich', calories: 270, protein: 12, fat: 11, carbs: 30, fiber: 2, serving: '1 sandwich' },
  { name: 'Peanut butter toast', calories: 270, protein: 11, fat: 17, carbs: 21, fiber: 4, serving: '1 slice + 2tbsp PB' },
  { name: 'Avocado toast', calories: 220, protein: 5, fat: 12, carbs: 24, fiber: 5, serving: '1 slice bread + 1/2 avo' },
  { name: 'Avocado toast with egg', calories: 290, protein: 11, fat: 17, carbs: 24, fiber: 5, serving: '1 slice + 1/2 avo + egg' },
  { name: 'Caesar salad', calories: 330, protein: 18, fat: 21, carbs: 16, fiber: 2, serving: '1 bowl' },
  { name: 'Greek salad', calories: 200, protein: 7, fat: 14, carbs: 11, fiber: 3, serving: '1 bowl' },
  { name: 'Poke bowl', calories: 450, protein: 25, fat: 14, carbs: 52, fiber: 3, serving: '1 bowl' },
  { name: 'Burrito bowl', calories: 480, protein: 26, fat: 16, carbs: 56, fiber: 8, serving: '1 bowl' },
  { name: 'Tacos (chicken, 2)', calories: 340, protein: 22, fat: 12, carbs: 34, fiber: 3, serving: '2 tacos' },
  { name: 'Tacos (beef, 2)', calories: 370, protein: 20, fat: 16, carbs: 34, fiber: 3, serving: '2 tacos' },
  { name: 'Nachos (loaded)', calories: 520, protein: 20, fat: 28, carbs: 46, fiber: 5, serving: '1 plate' },
  { name: 'Fried rice', calories: 340, protein: 10, fat: 12, carbs: 48, fiber: 2, serving: '1 cup (250g)' },
  { name: 'Pad Thai', calories: 440, protein: 18, fat: 16, carbs: 54, fiber: 2, serving: '1 plate' },
  { name: 'Green curry (with rice)', calories: 500, protein: 22, fat: 20, carbs: 54, fiber: 2, serving: '1 bowl' },
  { name: 'Tom yum soup', calories: 120, protein: 10, fat: 3, carbs: 14, fiber: 1, serving: '1 bowl (300ml)' },
  { name: 'Pho (beef)', calories: 350, protein: 22, fat: 8, carbs: 44, fiber: 1, serving: '1 bowl' },
  { name: 'Ramen', calories: 500, protein: 22, fat: 18, carbs: 58, fiber: 2, serving: '1 bowl' },
  { name: 'Dumplings (pork, 6)', calories: 240, protein: 12, fat: 8, carbs: 30, fiber: 1, serving: '6 dumplings' },
  { name: 'Spring rolls (2)', calories: 200, protein: 5, fat: 10, carbs: 22, fiber: 1, serving: '2 rolls' },
  { name: 'Sushi (salmon nigiri, 2 pieces)', calories: 93, protein: 5, fat: 2, carbs: 14, fiber: 0, serving: '2 pieces' },
  { name: 'Sushi roll (6 pieces)', calories: 250, protein: 9, fat: 4, carbs: 42, fiber: 1, serving: '1 roll (6 pieces)' },
  { name: 'Pizza slice (pepperoni)', calories: 298, protein: 13, fat: 12, carbs: 34, fiber: 2, serving: '1 slice (107g)' },
  { name: 'Pizza slice (margherita)', calories: 250, protein: 11, fat: 10, carbs: 30, fiber: 2, serving: '1 slice' },
  { name: 'Pizza slice (Hawaiian)', calories: 260, protein: 12, fat: 9, carbs: 32, fiber: 1, serving: '1 slice' },
  { name: 'Hamburger (homemade)', calories: 430, protein: 26, fat: 20, carbs: 34, fiber: 2, serving: '1 burger' },
  { name: 'Cheeseburger (homemade)', calories: 500, protein: 30, fat: 25, carbs: 34, fiber: 2, serving: '1 burger' },
  { name: 'Fish and chips', calories: 600, protein: 25, fat: 28, carbs: 56, fiber: 4, serving: '1 serve' },
  { name: 'Meat pie', calories: 400, protein: 14, fat: 22, carbs: 34, fiber: 2, serving: '1 pie (175g)' },
  { name: 'Sausage roll', calories: 310, protein: 10, fat: 20, carbs: 22, fiber: 1, serving: '1 roll (130g)' },
  { name: 'Shepherd\'s pie', calories: 350, protein: 18, fat: 16, carbs: 32, fiber: 3, serving: '1 serve (250g)' },
  { name: 'Soup (pumpkin)', calories: 120, protein: 3, fat: 4, carbs: 18, fiber: 3, serving: '1 bowl (300ml)' },
  { name: 'Soup (chicken and veg)', calories: 150, protein: 12, fat: 4, carbs: 16, fiber: 2, serving: '1 bowl (300ml)' },
  { name: 'Soup (minestrone)', calories: 130, protein: 5, fat: 3, carbs: 20, fiber: 4, serving: '1 bowl (300ml)' },

  // ============================================================
  // BREAKFAST ITEMS (~22)
  // ============================================================
  { name: 'Pancakes (2, plain)', calories: 252, protein: 7, fat: 8, carbs: 38, fiber: 1, serving: '2 pancakes' },
  { name: 'Pancakes with maple syrup', calories: 360, protein: 7, fat: 8, carbs: 64, fiber: 1, serving: '2 pancakes + 2 tbsp syrup' },
  { name: 'Waffles (frozen, 2)', calories: 190, protein: 4, fat: 6, carbs: 30, fiber: 1, serving: '2 waffles' },
  { name: 'French toast (2 slices)', calories: 292, protein: 10, fat: 14, carbs: 32, fiber: 1, serving: '2 slices' },
  { name: 'Porridge (with milk)', calories: 230, protein: 9, fat: 6, carbs: 35, fiber: 4, serving: '1 bowl' },
  { name: 'Overnight oats', calories: 310, protein: 12, fat: 10, carbs: 42, fiber: 5, serving: '1 jar (250g)' },
  { name: 'Bircher muesli', calories: 280, protein: 8, fat: 8, carbs: 42, fiber: 4, serving: '1 bowl (200g)' },
  { name: 'Acai bowl', calories: 380, protein: 6, fat: 12, carbs: 62, fiber: 6, serving: '1 bowl (300g)' },
  { name: 'Smoothie bowl', calories: 320, protein: 8, fat: 8, carbs: 54, fiber: 6, serving: '1 bowl (300g)' },
  { name: 'Toast with butter (1 slice)', calories: 140, protein: 3, fat: 6, carbs: 15, fiber: 1, serving: '1 slice + butter' },
  { name: 'Toast with jam (1 slice)', calories: 130, protein: 3, fat: 1, carbs: 27, fiber: 1, serving: '1 slice + 1 tbsp jam' },
  { name: 'Toast with Vegemite (1 slice)', calories: 100, protein: 5, fat: 1, carbs: 16, fiber: 1, serving: '1 slice + 1 tsp' },
  { name: 'Cereal with milk', calories: 220, protein: 7, fat: 4, carbs: 38, fiber: 2, serving: '1 bowl (30g cereal + 150ml milk)' },
  { name: 'Weet-Bix with milk (2)', calories: 195, protein: 8, fat: 4, carbs: 30, fiber: 3, serving: '2 biscuits + 150ml milk' },
  { name: 'Bacon and eggs (2 + 2)', calories: 262, protein: 18, fat: 20, carbs: 0, fiber: 0, serving: '2 bacon + 2 eggs' },
  { name: 'Big breakfast (cafe)', calories: 750, protein: 38, fat: 42, carbs: 50, fiber: 4, serving: '1 plate' },
  { name: 'Eggs benedict', calories: 550, protein: 24, fat: 34, carbs: 32, fiber: 1, serving: '1 serve (2 eggs)' },
  { name: 'Breakfast burrito', calories: 420, protein: 18, fat: 18, carbs: 44, fiber: 3, serving: '1 burrito' },
  { name: 'Croissant (plain)', calories: 231, protein: 5, fat: 12, carbs: 26, fiber: 1, serving: '1 croissant (57g)' },
  { name: 'Croissant (ham and cheese)', calories: 350, protein: 15, fat: 19, carbs: 28, fiber: 1, serving: '1 filled croissant' },
  { name: 'Milo (1 cup with milk)', calories: 200, protein: 9, fat: 5, carbs: 30, fiber: 1, serving: '2 tbsp Milo + 250ml milk' },
  { name: 'Up & Go (chocolate)', calories: 210, protein: 8, fat: 5, carbs: 33, fiber: 3, serving: '1 box (250ml)' },

  // ============================================================
  // AUSTRALIAN-SPECIFIC (~16)
  // ============================================================
  { name: 'Tim Tam (1 biscuit)', calories: 95, protein: 1, fat: 5, carbs: 12, fiber: 0, serving: '1 biscuit (18g)' },
  { name: 'Tim Tams (2 biscuits)', calories: 190, protein: 2, fat: 9, carbs: 24, fiber: 1, serving: '2 biscuits (36g)' },
  { name: 'Lamington', calories: 280, protein: 4, fat: 12, carbs: 40, fiber: 1, serving: '1 lamington (80g)' },
  { name: 'Meat pie (Four\'N Twenty)', calories: 380, protein: 12, fat: 21, carbs: 34, fiber: 1, serving: '1 pie (175g)' },
  { name: 'Sausage roll (party size, 2)', calories: 200, protein: 6, fat: 13, carbs: 14, fiber: 0, serving: '2 small rolls' },
  { name: 'Vegemite toast (2 slices)', calories: 200, protein: 8, fat: 2, carbs: 32, fiber: 2, serving: '2 slices + Vegemite' },
  { name: 'Fairy bread (1 slice)', calories: 125, protein: 2, fat: 5, carbs: 18, fiber: 0, serving: '1 slice' },
  { name: 'Pavlova (1 slice)', calories: 280, protein: 3, fat: 10, carbs: 44, fiber: 0, serving: '1 slice' },
  { name: 'Anzac biscuit', calories: 130, protein: 2, fat: 6, carbs: 18, fiber: 1, serving: '1 biscuit (30g)' },
  { name: 'Chicken parma', calories: 646, protein: 42, fat: 30, carbs: 52, fiber: 3, serving: '1 serve' },
  { name: 'Bunnings sausage sizzle', calories: 360, protein: 14, fat: 19, carbs: 30, fiber: 2, serving: '1 sausage + bread + onion' },
  { name: 'Chiko Roll', calories: 210, protein: 5, fat: 10, carbs: 24, fiber: 2, serving: '1 roll (78g)' },
  { name: 'Dim sim (fried, 1)', calories: 90, protein: 3, fat: 5, carbs: 8, fiber: 0, serving: '1 dim sim (50g)' },
  { name: 'Pie floater', calories: 500, protein: 18, fat: 24, carbs: 48, fiber: 4, serving: '1 serve' },
  { name: 'Caramello Koala', calories: 90, protein: 1, fat: 4, carbs: 13, fiber: 0, serving: '1 koala (15g)' },
  { name: 'Shapes (BBQ, small box)', calories: 420, protein: 7, fat: 17, carbs: 58, fiber: 2, serving: '1 box (80g)' },

  // ============================================================
  // FAST FOOD (~28)
  // ============================================================
  { name: 'McDonald\'s Big Mac', calories: 550, protein: 25, fat: 30, carbs: 42, fiber: 3, serving: '1 burger' },
  { name: 'McDonald\'s Quarter Pounder', calories: 520, protein: 30, fat: 26, carbs: 40, fiber: 2, serving: '1 burger' },
  { name: 'McDonald\'s Cheeseburger', calories: 300, protein: 15, fat: 12, carbs: 33, fiber: 2, serving: '1 burger' },
  { name: 'McDonald\'s McChicken', calories: 400, protein: 14, fat: 21, carbs: 39, fiber: 2, serving: '1 burger' },
  { name: 'McDonald\'s medium fries', calories: 340, protein: 4, fat: 16, carbs: 44, fiber: 4, serving: '1 medium' },
  { name: 'McDonald\'s Chicken McNuggets (6)', calories: 250, protein: 15, fat: 15, carbs: 15, fiber: 1, serving: '6 nuggets' },
  { name: 'McDonald\'s Hash Brown', calories: 140, protein: 1, fat: 8, carbs: 16, fiber: 1, serving: '1 hash brown' },
  { name: 'McDonald\'s Egg McMuffin', calories: 300, protein: 17, fat: 13, carbs: 29, fiber: 2, serving: '1 muffin' },
  { name: 'Hungry Jack\'s / Burger King Whopper', calories: 657, protein: 28, fat: 40, carbs: 49, fiber: 2, serving: '1 burger' },
  { name: 'KFC Original piece (thigh)', calories: 290, protein: 18, fat: 19, carbs: 10, fiber: 0, serving: '1 piece' },
  { name: 'KFC Original piece (breast)', calories: 320, protein: 29, fat: 17, carbs: 11, fiber: 0, serving: '1 piece' },
  { name: 'KFC Zinger burger', calories: 480, protein: 24, fat: 22, carbs: 44, fiber: 2, serving: '1 burger' },
  { name: 'KFC chips (regular)', calories: 290, protein: 4, fat: 13, carbs: 38, fiber: 3, serving: '1 regular' },
  { name: 'KFC coleslaw', calories: 130, protein: 1, fat: 10, carbs: 10, fiber: 1, serving: '1 serve' },
  { name: 'Subway 6-inch (turkey breast)', calories: 280, protein: 18, fat: 4, carbs: 46, fiber: 5, serving: '6-inch sub' },
  { name: 'Subway 6-inch (chicken teriyaki)', calories: 370, protein: 26, fat: 5, carbs: 57, fiber: 5, serving: '6-inch sub' },
  { name: 'Subway 6-inch (meatball)', calories: 480, protein: 22, fat: 18, carbs: 54, fiber: 6, serving: '6-inch sub' },
  { name: 'Subway footlong (turkey breast)', calories: 560, protein: 36, fat: 8, carbs: 92, fiber: 10, serving: '12-inch sub' },
  { name: 'Nando\'s chicken breast (1/4)', calories: 240, protein: 38, fat: 9, carbs: 0, fiber: 0, serving: '1/4 chicken' },
  { name: 'Nando\'s chicken thigh (1/4)', calories: 290, protein: 28, fat: 19, carbs: 0, fiber: 0, serving: '1/4 chicken' },
  { name: 'Nando\'s chips (regular)', calories: 350, protein: 5, fat: 16, carbs: 45, fiber: 4, serving: '1 regular' },
  { name: 'Domino\'s pizza (1 slice, cheese)', calories: 220, protein: 9, fat: 8, carbs: 28, fiber: 1, serving: '1 slice (large)' },
  { name: 'Domino\'s pizza (1 slice, supreme)', calories: 260, protein: 11, fat: 11, carbs: 28, fiber: 2, serving: '1 slice (large)' },
  { name: 'Domino\'s garlic bread (2 pieces)', calories: 180, protein: 4, fat: 7, carbs: 24, fiber: 1, serving: '2 pieces' },
  { name: 'Guzman y Gomez burrito', calories: 620, protein: 30, fat: 22, carbs: 70, fiber: 8, serving: '1 burrito' },
  { name: 'Red Rooster quarter chicken', calories: 310, protein: 30, fat: 18, carbs: 6, fiber: 0, serving: '1/4 chicken' },
  { name: 'Boost Juice (banana buzz)', calories: 300, protein: 10, fat: 2, carbs: 60, fiber: 3, serving: '1 regular' },
  { name: 'Grill\'d burger (Simply Grill\'d)', calories: 480, protein: 30, fat: 18, carbs: 44, fiber: 3, serving: '1 burger' },

  // ============================================================
  // BAKED GOODS (~16)
  // ============================================================
  { name: 'Muffin (blueberry)', calories: 350, protein: 5, fat: 14, carbs: 50, fiber: 2, serving: '1 large muffin (113g)' },
  { name: 'Muffin (chocolate chip)', calories: 400, protein: 5, fat: 18, carbs: 56, fiber: 2, serving: '1 large muffin (113g)' },
  { name: 'Muffin (bran)', calories: 270, protein: 5, fat: 10, carbs: 42, fiber: 5, serving: '1 muffin (100g)' },
  { name: 'Scone (plain)', calories: 210, protein: 4, fat: 7, carbs: 32, fiber: 1, serving: '1 scone (60g)' },
  { name: 'Scone (with jam and cream)', calories: 360, protein: 5, fat: 14, carbs: 52, fiber: 1, serving: '1 scone + toppings' },
  { name: 'Croissant (chocolate)', calories: 280, protein: 5, fat: 15, carbs: 31, fiber: 1, serving: '1 croissant (65g)' },
  { name: 'Danish pastry', calories: 266, protein: 5, fat: 14, carbs: 30, fiber: 1, serving: '1 pastry (71g)' },
  { name: 'Doughnut (glazed)', calories: 269, protein: 4, fat: 15, carbs: 31, fiber: 1, serving: '1 doughnut (60g)' },
  { name: 'Doughnut (jam-filled)', calories: 289, protein: 5, fat: 16, carbs: 33, fiber: 1, serving: '1 doughnut (65g)' },
  { name: 'Cake (chocolate, 1 slice)', calories: 352, protein: 5, fat: 14, carbs: 51, fiber: 2, serving: '1 slice (80g)' },
  { name: 'Cake (carrot, 1 slice)', calories: 320, protein: 4, fat: 16, carbs: 40, fiber: 1, serving: '1 slice (80g)' },
  { name: 'Cheesecake (1 slice)', calories: 320, protein: 5, fat: 18, carbs: 34, fiber: 0, serving: '1 slice (80g)' },
  { name: 'Cookie (chocolate chip)', calories: 150, protein: 2, fat: 7, carbs: 20, fiber: 1, serving: '1 cookie (35g)' },
  { name: 'Shortbread biscuit', calories: 80, protein: 1, fat: 4, carbs: 10, fiber: 0, serving: '1 biscuit (16g)' },
  { name: 'Brownie', calories: 230, protein: 3, fat: 10, carbs: 33, fiber: 1, serving: '1 piece (56g)' },
  { name: 'Cinnamon scroll', calories: 360, protein: 5, fat: 14, carbs: 52, fiber: 1, serving: '1 scroll (85g)' },

  // ============================================================
  // BABY & KIDS FOODS (~12)
  // ============================================================
  { name: 'Baby food pouch (fruit)', calories: 50, protein: 0, fat: 0, carbs: 12, fiber: 1, serving: '1 pouch (90g)' },
  { name: 'Baby food pouch (veg + protein)', calories: 60, protein: 3, fat: 1, carbs: 10, fiber: 1, serving: '1 pouch (120g)' },
  { name: 'Baby rice cereal', calories: 60, protein: 1, fat: 0, carbs: 13, fiber: 0, serving: '2 tbsp dry (15g)' },
  { name: 'Kids yoghurt pouch', calories: 70, protein: 2, fat: 1, carbs: 13, fiber: 0, serving: '1 pouch (70g)' },
  { name: 'Fish fingers (frozen, 4)', calories: 200, protein: 10, fat: 8, carbs: 20, fiber: 1, serving: '4 fingers (100g)' },
  { name: 'Chicken nuggets (6)', calories: 270, protein: 14, fat: 16, carbs: 16, fiber: 1, serving: '6 nuggets (100g)' },
  { name: 'Chicken nuggets (10)', calories: 450, protein: 23, fat: 27, carbs: 27, fiber: 1, serving: '10 nuggets (167g)' },
  { name: 'Mini pizza (frozen)', calories: 220, protein: 8, fat: 8, carbs: 28, fiber: 2, serving: '1 mini pizza (100g)' },
  { name: 'Spaghetti hoops (canned)', calories: 120, protein: 3, fat: 1, carbs: 24, fiber: 1, serving: '1/2 can (200g)' },
  { name: 'Cheese stick / string cheese', calories: 80, protein: 7, fat: 5, carbs: 1, fiber: 0, serving: '1 stick (28g)' },
  { name: 'Petit Miam yoghurt', calories: 62, protein: 3, fat: 2, carbs: 8, fiber: 0, serving: '1 tube (70g)' },
  { name: 'Tiny Teddy biscuits (1 pack)', calories: 105, protein: 2, fat: 3, carbs: 18, fiber: 0, serving: '1 pack (25g)' },
]

/**
 * Search common foods by query string.
 * Returns fuzzy-matched results sorted by relevance.
 */
export function searchCommonFoods(query) {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase().trim()
  const words = q.split(/\s+/)

  return COMMON_FOODS
    .map((food) => {
      const name = food.name.toLowerCase()
      // Exact substring match scores highest
      if (name.includes(q)) return { ...food, score: 100 }
      // All words match
      if (words.every(w => name.includes(w))) return { ...food, score: 80 }
      // Any word matches
      const matchCount = words.filter(w => name.includes(w)).length
      if (matchCount > 0) return { ...food, score: matchCount * 30 }
      return null
    })
    .filter(Boolean)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
}
